version: '3.8'
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=ashu-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.31.35.233:9092
      
      
